name: Node Build Workflow

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'
      upload-artifacts:
        required: false
        type: boolean
        default: false
      artifact-name:
        required: false
        type: string
        default: 'build-output'
      artifact-path:
        required: false
        type: string
        default: 'dist/'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    
    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Cache Next.js build
      uses: actions/cache@v3
      with:
        path: |
          .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-
          
    - name: Install dependencies
      run: npm ci
    
    - name: Temporarily modify Babel config for build
      run: |
        if [ -f .babelrc ]; then mv .babelrc .babelrc.backup; fi
        if [ -f babel.config.js ]; then mv babel.config.js babel.config.js.backup; fi
    
    - name: Build
      run: npm run build

    - name: Restore Babel config
      run: |
        if [ -f .babelrc.backup ]; then mv .babelrc.backup .babelrc; fi
        if [ -f babel.config.js.backup ]; then mv babel.config.js.backup babel.config.js; fi
      
    - name: Ensure artifact directory exists
      if: ${{ inputs.upload-artifacts }}
      run: mkdir -p ${{ inputs.artifact-path }}

    - name: Upload build artifacts
      if: ${{ inputs.upload-artifacts }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}
        if-no-files-found: error